import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Text } from "@mantine/core"
import { FileUpload } from "../components/FileUpload"
import dynamic from "next/dynamic"
import { useState } from "react"
import { figToJson } from "../lib/fig2json"

const ReactJson = dynamic(() => import("react-json-view"), {
  ssr: false
})

const Home: NextPage = () => {
  const [json, setJson] = useState<object | null>(null)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Text size='xl'>Figma to JSON</Text>
        <FileUpload
          onDrop={async (files) => {
            const file = files[0]
            const buffer = await file.arrayBuffer()
            const json = figToJson(buffer)
            setJson(json)
          }}
        />
        {json && <ReactJson src={json} collapsed={true} theme='twilight' />}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
